DB_URL: jdbc:postgresql://localhost:5432/appointment_service1?useUnicode=yes&characterEncoding=UTF-8
DB_USERNAME: postgres
DB_PASSWORD: admin

server:
  port: 8082
  max-http-request-header-size: 16KB

spring:
  application:
    name: appointment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 300000
  jpa:
    open-in-view: false
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        types:
          print:
            banner: false
  flyway:
    table: flyway_schema_history
    baseline-description: "<< Flyway Appointment Baseline >>"
    baseline-version: 1
    baseline-on-migrate: true
    locations: "classpath:db/migration/appointment"
    enabled: true

logging:
  file:
    name: /var/log/appointment_service/appointment_service.log
  level:
    root: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# JWT Configuration
jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000

# Email Configuration
email:
  smtp:
    host: smtp.hostinger.com
    port: 587
    protocols: TLSv1.3
    auth: true
    starttls: true
    trust: smtp.hostinger.com
    protocol: smtp
  from:
    address: noreply@batech.info
    password: Admin@4209211
    name: OTP Lawyer Service
  to: usasid@gmail.com
  subject: Appointment Booking Notification
  body: >
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    </head>
    <body>
    <p>Dear Lawyer,</p>
    <p>A customer has booked an <strong>appointment</strong> with you.</p>
    <p>
        <strong>Appointment Details:</strong><br>
        Customer Name: <strong>%{appointment.customerName}</strong><br>
        Date: <strong>%{appointment.date}</strong><br>
        Time: <strong>%{appointment.time}</strong><br>
        Appointment Type: <strong>%{appointment.type}</strong>
    </p>
    <p>
        Please review the booking request and choose one of the following actions:
    </p>
    <ul>
        <li><strong>Accept</strong> the appointment</li>
        <li><strong>Reject</strong> the appointment</li>
    </ul>
    <p>
    You can manage this appointment directly from your <strong>dashboard</strong> in the application.
    </p>
    <p>
    If you believe this request was made in error or have any concerns, please contact our Support Team immediately.
    </p>
    <br>
    <p>Regards,<br>
    </body>
    </html>

service:
  auth-url: "http://localhost:8080"
  profile-url: "http://localhost:8081"
  internal-secret: "VMY0qcWu+mDK4o4ggmwZxg=="

internal:
  api:
    secret: "VMY0qcWu+mDK4o4ggmwZxg=="
