DB_URL: jdbc:postgresql://db:9876/appointment_service?useUnicode=yes&characterEncoding=UTF-8
DB_USERNAME: postgres
DB_PASSWORD: lawyer@database

server:
  port: 9213
  max-http-request-header-size: 16KB

spring:
  application:
    name: appointment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 300000
  jpa:
    open-in-view: false
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        types:
          print:
            banner: false
  flyway:
    table: flyway_schema_history
    baseline-description: "<< Flyway Appointment Baseline >>"
    baseline-version: 1
    baseline-on-migrate: true
    locations: "classpath:db/migration/appointment"
    enabled: true

logging:
  level:
    root: INFO

# JWT Configuration
jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000

service:
  auth-url: "http://localhost:9211"
  profile-url: "http://localhost:9212"
  internal-secret: "VMY0qcWu+mDK4o4ggmwZxg=="

internal:
  api:
    secret: "VMY0qcWu+mDK4o4ggmwZxg=="
